apiVersion: v1
kind: Service
metadata:
  name: dcrx-api
  labels:
    run: dcrx-api
spec:
  type: LoadBalancer
  ports:
    - name: http
      protocol: TCP
      port: 2277
      targetPort: 2277
  selector:
    app: dcrx-api