apiVersion: v1
kind: Service
metadata:
  name: "{{ .Release.Name }}-dcrx-api"
  labels:
    run: "{{ .Release.Name }}-dcrx-api"
spec:
  type: LoadBalancer
  ports:
    - name: http
      protocol: TCP
      port: 2277
      targetPort: 2277
  selector:
    app: "{{ .Release.Name }}-dcrx-api"